Add integration tests
ansible-community/ansible.plugin_builder pull request #5
Opened 2022-02-23 07:08 UTC by NilashishC

Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- Add integration tests

2022-02-23 13:25 UTC, ashwini-mhatre approved these changes

2022-02-28 17:33 UTC, GomathiselviS commented
recheck

2022-02-28 18:01 UTC, GomathiselviS commented
recheck

2022-02-28 18:58 UTC, goneri commented
recheck

2022-02-28 19:05 UTC, goneri commented
recheck

2022-02-28 19:39 UTC, goneri commented
recheck

2022-02-28 19:43 UTC, goneri commented
recheck

2022-02-28 19:52 UTC, goneri commented
recheck

2022-03-03 05:27 UTC, NilashishC commented
recheck

2022-03-03 14:57 UTC, goneri commented
recheck

2022-03-10 06:31 UTC, NilashishC commented
recheck

2022-03-10 06:51 UTC, NilashishC commented
@goneri it is now failing with an unrelated error? Could you please help?

2022-03-10 19:38 UTC, goneri commented
recheck

2022-03-10 20:00 UTC, goneri commented
recheck

2022-03-10 20:03 UTC, goneri requested changes

2022-03-10 20:03 UTC, goneri commented on zuul.yaml
> +---
Please, remove this file from your PR.

2022-03-30 18:00 UTC, GomathiselviS commented
recheck

2022-09-20 13:06 UTC, closed without merging